// src/modules/common/order/app.vue
<!--
 * @Date: 2020-09-08 11:06:11
 * @LastEditTime: 2020-09-15 15:58:35
-->
<template>
  <div class="order">
    <van-tabs
      v-model="active"
      @change="change"
      sticky
      line-width="22px"
      line-height="4px"
      color="#1a61dc"
      title-active-color="#1a61dc"
      background="#F5F5F7"
      title-inactive-color="#999999"
    >
      <van-tab
        v-for="index in OrderTypes"
        :key="index.value"
        :name="index.value"
        :title="index.title"
      >
        <van-list
          v-model="loading"
          :finished="finished"
          finished-text="- 没有更多了 -"
          @load="onLoad"
          v-show="list.length"
          class="order__list"
        >
          <van-cell v-for="item in list" :key="item.code" class="order__item">
            <div class="order__item-head">
              <span class="order__item-head-no">
                订单号：{{ item.orderId }}
              </span>
              <span class="order__item-head-status">
                {{
                  typeof TraceStatus[item.status] === 'function'
                    ? TraceStatus[item.status](item.productTypeCode)
                    : TraceStatus[item.status]
                }}
              </span>
            </div>
            <div class="order__item-goods">
              <img
                :class="
                  item.status === TRACE_STATUS_6
                    ? 'order__item-goods-unimg'
                    : 'order__item-goods-img'
                "
                :src="'/file' + item.iconUrl"
              />
              <span class="order__item-goods-name">
                {{ item.goodsName }}
                <b
                  :class="
                    item.status === TRACE_STATUS_6
                      ? 'order__item-goods-name--untype'
                      : 'order__item-goods-name--type'
                  "
                >
                  {{ ProductTypes[item.productTypeCode] }}
                </b>
              </span>
              <span class="order__item-goods-other">
                <span>x{{ item.amount }}</span>
                <span class="price">
                  ￥{{ (item.price / TRANSTEMP, PRECISION) }}
                </span>
              </span>
            </div>
            <div class="order__item-extra">
              <span class="order__item-extra-item">
                购买时间：{{ item.createTime }}
              </span>
              <span
                v-show="item.productTypeCode === PRODUCT_TYPE_4"
                class="order__item-extra-item"
              >
                充值账号：{{ item.rechargeAccount }}
              </span>
            </div>
            <div class="order__item-bottom">
              <div v-if="item.status === TRACE_STATUS_1">
                <div class="order__item-bottom-text">
                  <span class="order__item-bottom-text--text">待付合计:</span>
                  <span class="order__item-bottom-text--money">
                    &nbsp;￥{{
                      getFloat(
                        (item.amount * item.price) / TRANSTEMP,
                        PRECISION
                      )
                    }}
                  </span>
                </div>
              </div>
              <div v-else-if="item.status === TRACE_STATUS_2">
                <div class="order__item-bottom-text">
                  <span class="order__item-bottom-text--text">合计:</span>
                  <span class="order__item-bottom-text--money">
                    &nbsp;￥{{
                      getFloat(
                        (item.amount * item.price) / TRANSTEMP,
                        PRECISION
                      )
                    }}
                  </span>
                </div>
              </div>
              <div v-else-if="item.status === TRACE_STATUS_4">
                <div class="order__item-bottom-text">
                  <span class="order__item-bottom-text--text">合计:</span>
                  <span class="order__item-bottom-text--money">
                    &nbsp;￥{{
                      getFloat(
                        (item.amount * item.price) / TRANSTEMP,
                        PRECISION
                      )
                    }}
                  </span>
                </div>
              </div>
              <div v-else-if="item.status === TRACE_STATUS_5">
                <div class="order__item-bottom-text">
                  <span class="order__item-bottom-text--text">合计:</span>
                  <span class="order__item-bottom-text--money">
                    &nbsp;￥{{
                      getFloat(
                        (item.amount * item.price) / TRANSTEMP,
                        PRECISION
                      )
                    }}
                  </span>
                </div>
              </div>
              <div v-else-if="item.status === TRACE_STATUS_6">
                <div class="order__item-bottom-text">
                  <span class="order__item-bottom-text--text">合计:</span>
                  <span class="order__item-bottom-text--unmoney">
                    &nbsp;￥{{
                      getFloat(
                        (item.amount * item.price) / TRANSTEMP,
                        PRECISION
                      )
                    }}
                  </span>
                </div>
              </div>

              <div class="order__item-bottom-btn">
                <span class="order__item-bottom--text">
                  <div
                    v-show="item.status === TRACE_STATUS_1"
                    class="order__item-bottom--pay"
                  >
                    等待买家付款
                  </div>
                </span>

                <div v-if="item.status === TRACE_STATUS_1">
                  <div class="order__item-bottom-btn--ghost" @click="kefuModal">
                    联系客服
                  </div>
                  <div
                    class="order__item-bottom-btn--primary"
                    @click="_pay(item.orderId)"
                  >
                    继续支付
                  </div>
                </div>

                <div v-else-if="item.status === TRACE_STATUS_2">
                  <div class="order__item-bottom-btn--ghost" @click="kefuModal">
                    联系客服
                  </div>
                </div>

                <div v-else-if="item.status === TRACE_STATUS_4">
                  <div
                    class="order__item-bottom-btn--primary"
                    v-show="
                      item.productTypeCode === PRODUCT_TYPE_1 ||
                        item.productTypeCode === PRODUCT_TYPE_2 ||
                        item.productTypeCode === PRODUCT_TYPE_3
                    "
                    @click="
                      window.location.href = `/card.html#/?orderId=${item.orderId}`
                    "
                  >
                    查看卡券
                  </div>
                </div>
              </div>
            </div>
          </van-cell>
        </van-list>
        <div v-show="!list.length && !loading" class="empty">
          <img :src="empty" />
          <div class="empty-text">您还没有订单</div>
        </div>
      </van-tab>
    </van-tabs>
    <form id="pay_form" :action="payUrl" method="post" ref="formRef">
      <input
        id="order_info"
        type="text"
        name="orderInfo"
        :value="orderInfo"
        style="display: none"
      />
    </form>
  </div>
</template>
<script>
import {
  getOrderByOrderId,
  pay,
  searchUserSubscribeOrderList,
  shiluPay,
} from '@/services/app';
import {
  ProductTypes,
  TraceStatus,
  TRACE_STATUS_0,
  TRACE_STATUS_1,
  TRACE_STATUS_2,
  TRACE_STATUS_3,
  TRACE_STATUS_4,
  TRACE_STATUS_5,
  TRACE_STATUS_6,
  PRODUCT_TYPE_1,
  PRODUCT_TYPE_2,
  PRODUCT_TYPE_3,
  PRODUCT_TYPE_4,
  TRANSTEMP,
  PRECISION,
} from '@/const';
import { getQueryVariable, getFloat, getChannel } from '@/utils';
import { OrderTypes } from '@/const';
import empty from '@/assets/images/empty.png';

export default {
  name: 'order',
  data() {
    return {
      active: '',
      OrderTypes,
      empty,

      currPage: 1,
      pageSize: 10,

      list: [],

      loading: false,
      finished: false,
      visible: false,

      payUrl: '',
      orderInfo: '',

      ProductTypes,
      TraceStatus,
      TRACE_STATUS_0,
      TRACE_STATUS_1,
      TRACE_STATUS_2,
      TRACE_STATUS_3,
      TRACE_STATUS_4,
      TRACE_STATUS_5,
      TRACE_STATUS_6,
      PRODUCT_TYPE_1,
      PRODUCT_TYPE_2,
      PRODUCT_TYPE_3,
      PRODUCT_TYPE_4,
      TRANSTEMP,
      PRECISION,
    };
  },
  created() {
    this.tabIndex();
    this.fetch();
  },

  methods: {
    getFloat,

    change(name, title) {
      this.currPage = 1;
      this.list = [];
      this.loading = true;
      this.fetch();
    },

    //上拉加载
    onLoad() {
      if (this.pageSize * this.currPage > this.list.length) {
        this.finished = true;
      } else {
        this.currPage++;
        this.fetch((data) => {
          if (data.list.length < this.pageSize) this.finished = true;
        });
        this.loading = true;
      }
    },

    async fetch(callBack) {
      try {
        const [err, data, msg] = await searchUserSubscribeOrderList({
          pageSize: this.pageSize,
          currPage: this.currPage,
          statusArray: this.active,
        });
        if (!err) {
          this.loading = false;
          callBack && callBack(data);
          this.list.push(...data.list);
        }
      } catch (error) {}
    },

    tabIndex() {
      const tabIndex = parseInt(getQueryVariable('index')) || '';
      this.active = tabIndex;
    },

    kefuModal() {
      this.$dialog.alert({
        title: '咨询商品问题,请添加客服QQ(2045879978)',
        confirmButtonColor: '#1a61dc',
      });
    },

    async _pay(orderId) {
      try {
        if (getChannel() == 'WECHAT' || getChannel() == 'PLAT3_WECHAT') {
          //wx公众号支付
          const [err, data, msg] = await pay({ orderId });
          if (!err) {
            this.getList(orderId);
            this.wxpay(data);
          } else this.$toast.fail(msg);
        } else if (getChannel() == 'PLAT3') {
          //H5支付
          this.shilu(orderId);
        }
      } catch (error) {}
    },

    //wx-h5--支付
    async shilu(orderId) {
      try {
        const [err, data, msg] = await shiluPay({ orderId });
        if (!err) {
          //这里唤起了H5支付 通过form的action
          this.payUrl = data.payUrl;
          this.orderInfo = data.orderInfo;
          this.$toast.loading({ forbidClick: true });
          this.$refs.formRef.submit();
        } else this.$toast.fail(msg);
      } catch (error) {}
    },

    wxpay({ appId, timestamp, nonceStr, signType, paySign, orderdetail }) {
      WeixinJSBridge.invoke(
        'getBrandWCPayRequest',
        {
          appId, //公众号名称，由商户传入
          timeStamp: timestamp, //时间戳，自1970年以来的秒数
          nonceStr, //随机串
          package: orderdetail,
          signType, //微信签名方式：
          paySign, //微信签名
        },
        (res) => {
          if (res.err_msg == 'get_brand_wcpay_request:cancel') {
            clearTimeout(timer);
          }
        }
      );
    },

    async getList(orderId) {
      try {
        const [err, data, msg] = await getOrderByOrderId({ orderId });
        if (!err) {
          if (data.payStatus === 1) {
            clearTimeout(timer);
            dispatchInit();
            this.$toast.success('支付成功');
          } else timer = setTimeout(() => getList(orderId), 1000);
        } else this.$toast.fail(msg);
      } catch (error) {}
    },
  },
};
</script>

// src/modules/common/card/app.jsx
import React, { useEffect, useState, useRef } from 'react';
import classnames from 'classnames';
import goods from '@/assets/images/goods.png';
import { InputNumber, Tabs as TabsComp } from '@/components/r';
import { getQueryVariable, getFloat, getChannel } from '@/utils';
import {
  searchGoodsByBrandCode,
  getBrandListInSameCategory,
  getOrderId,
  pay,
  getOrderByOrderId,
  shiluPay,
} from '@/services/app';
import { Toast, Modal } from 'antd-mobile';
import _ from 'lodash';
import { ProductTypes, TRANSTEMP, PRECISION } from '@/const';
import { Footer } from '@/components/r';

const data = [
  {
    title: '购买须知',
    key: 0,
  },
  {
    title: '使用说明',
    key: 1,
  },
];

export default (props) => {
  const brandCode = getQueryVariable('brandCode');

  const [list, setList] = useState([]);
  const [brandList, setBrandList] = useState([]);
  const [active, setActive] = useState(brandCode);
  const [activeTab, setActiveTab] = useState(0);
  const [goodsSelect, setGoodsSelect] = useState(0);
  const [amount, setAmount] = useState(1);
  const [skuCaches, setSkuCaches] = useState({});

  const [payUrl, setPayUrl] = useState('');
  const [orderInfo, setOrderInfo] = useState('');

  const inputRef = React.createRef();

  const formRef = useRef();

  useEffect(() => {
    // const goodsCode = getQueryVariable('goodsCode') || 0
    // setGoodsSelect(goodsCode);
    inputRef.current.setInputVal(1);
  }, [active]);

  let i = 0;

  useEffect(() => {
    if (!list.length) return;

    const goodsCode =
      i === 0 ? getQueryVariable('goodsCode') || list[0].code : list[0].code;
    setGoodsSelect(parseInt(goodsCode));
    i++;
  }, [list]);

  useEffect(() => {
    getBrandList(brandCode);
    initList(brandCode);
  }, []);

  const getBrandList = async (brandCode) => {
    try {
      const [err, data, msg] = await getBrandListInSameCategory(brandCode);
      if (!err) {
        // 将选中的对象置顶为第一个
        const index = data.findIndex((item) => item.code == brandCode);
        data.unshift(data.splice(index, 1)[0]);

        setBrandList(data);
      } else Toast.fail(msg);
    } catch (error) {}
  };

  const initList = async (brandCode) => {
    const cacheList = skuCaches[brandCode];

    if (!_.isEmpty(cacheList)) return setList(cacheList);

    try {
      Toast.loading();
      const [err, data, msg] = await searchGoodsByBrandCode({ brandCode });
      Toast.hide();
      if (!err) {
        setList(data || []);
        setSkuCaches({
          ...skuCaches,
          [brandCode]: data,
        });
        if (data[0].productTypeCode === 104) {
          window.location.href = `/credit.html#/?brandCode=${brandCode}`;
        }
      } else Toast.fail(msg, 1);
    } catch (error) {}
  };

  const _pay = async (orderId) => {
    try {
      if (getChannel() == 'PLAT3') {
        //H5支付
        shilu(orderId);
      } else if (getChannel() == 'WECHAT' || getChannel() == 'PLAT3_WECHAT') {
        //wx公众号支付
        const [err, data, msg] = await pay({ orderId });
        if (!err) {
          wxpay(data);
          getList(orderId);
        } else Toast.fail(msg);
      }
    } catch (error) {}
  };

  const validCallback = () => {
    if (!_.find(list, (item) => item.code === goodsSelect)?.code)
      return Toast.fail('请选择商品', 1);
    return {
      goodsCode: _.find(list, (item) => item.code === goodsSelect)?.code,
      amount,
    };
  };

  const shop = async () => {
    try {
      const params = validCallback();

      if (!params) return;

      let [err, data, msg] = await getOrderId(params);

      const { orderId } = data;

      if (!err) _pay(orderId);
      else Toast.fail(msg, 1);
    } catch (error) {}
  };

  const wxpay = ({
    appId,
    timestamp,
    nonceStr,
    signType,
    paySign,
    orderdetail,
  }) => {
    WeixinJSBridge.invoke(
      'getBrandWCPayRequest',
      {
        appId, //公众号名称，由商户传入
        timeStamp: timestamp, //时间戳，自1970年以来的秒数
        nonceStr, //随机串
        package: orderdetail,
        signType, //微信签名方式：
        paySign, //微信签名
      },
      (res) => {
        if (res.err_msg == 'get_brand_wcpay_request:cancel') {
          clearTimeout(timer);
        }
      }
    );
  };

  //wx-h5--支付
  const shilu = async (orderId) => {
    try {
      const [err, data, msg] = await shiluPay({ orderId });
      if (!err) {
        //这里唤起了H5支付 通过form的action
        setPayUrl(data.payUrl);
        setOrderInfo(data.orderInfo);
        Toast.loading();
        formRef.current.submit();
      } else Toast.fail(msg, 1);
    } catch (error) {}
  };

  const getList = async (orderId) => {
    try {
      const [err, data, msg] = await getOrderByOrderId({ orderId });
      if (!err) {
        if (data.payStatus === 1) {
          clearTimeout(timer);
          Toast.success('支付成功');
          window.location.href = `/order.html`;
        } else timer = setTimeout(() => getList(orderId), 1000);
      } else Toast.fail(msg, 1);
    } catch (error) {}
  };
  return (
    <>
      <div className="card-item">
        <div className="card-item__scroll-filter">
          {/* 隐藏ios滚动条 */}
          {/* <div
            style={{
              height: "86SUPX",
              // paddingTop: "4SUPX",
              overflowY: "hidden",
            }}
          > */}
          <ul>
            {_.map(brandList, (item, index) => (
              <li
                key={index}
                className={classnames({
                  active: active == brandList[index].code,
                })}
                onClick={() => {
                  const brandCode = brandList[index].code;
                  setActive(brandCode);
                  initList(brandCode);
                }}
              >
                {item.name}
              </li>
            ))}
          </ul>
          {/* </div> */}
          <div className="card-item__scroll-filter--line"></div>
        </div>
        <div className="card-item__goods">
          {/* 隐藏ios滚动条 */}
          <div
            style={{
              height: '408SUPX',
              paddingTop: '4SUPX',
              overflowY: 'hidden',
            }}
          >
            <ul>
              {_.map(list, (item, index) => (
                <li
                  key={index}
                  className={classnames({ active: goodsSelect === item.code })}
                  onClick={() => {
                    setGoodsSelect(item.code);
                    inputRef.current.setInputVal(1);
                  }}
                >
                  <div className="img-box">
                    <img src={item.iconUrl ? `/file${item.iconUrl}` : goods} />
                  </div>
                  <div className="info-wrap">
                    <span className="info-wrap-name">{item.shortName}</span>
                    <div className="info-wrap-price">
                      <span className="info-wrap-price__price">
                        <b style={{ fontSize: '24SUPX' }}>￥</b>
                        {getFloat(item.price / TRANSTEMP, PRECISION)}
                      </span>
                      <span className="info-wrap-price__face-price">
                        官方价{getFloat(item.facePrice / TRANSTEMP, PRECISION)}
                      </span>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="card-item__count-box">
          <div className="card-item__count-box-num">
            <span>
              <span className="card-item__count-box-num-title">购买数量</span>
              <span className="card-item__count-box-num-subtitle">
                最多可购买{' '}
                {
                  _.find(list, (item) => item.code === goodsSelect)
                    ?.singleBuyLimit
                }{' '}
                张
              </span>
            </span>
            <InputNumber
              min={1}
              max={
                _.find(list, (item) => item.code === goodsSelect)
                  ?.singleBuyLimit
              }
              defaultValue={1}
              onChange={(val) => setAmount(val)}
              ref={inputRef}
            />
          </div>

          <div className="card-item__count-box-suggestion">
            <span>
              使用有效期：<b>购买起24小时内</b>
            </span>
          </div>
        </div>

        <ul className="card-item__view">
          <li className="card-item__view-item line">
            <span className="card-item__view-item-title">商品名称</span>
            <span className="card-item__view-item-sub">
              {_.find(list, (item) => item.code === goodsSelect)?.name}
            </span>
          </li>
          <li className="card-item__view-item line">
            <span className="card-item__view-item-title">应付金额</span>
            <span className="card-item__view-item-price">
              <b>￥</b>
              {getFloat(
                (_.find(list, (item) => item.code === goodsSelect)?.price *
                  amount) /
                  TRANSTEMP,
                PRECISION
              )}
            </span>
          </li>
          <li className="card-item__view-item">
            <span className="card-item__view-item-title">商品标签</span>
            <div className="card-item__view-item-block">
              <span>
                {
                  ProductTypes[
                    _.find(list, (item) => item.code === goodsSelect)
                      ?.productTypeCode
                  ]
                }
              </span>
            </div>
          </li>
        </ul>

        <div className="card-item__html">
          <TabsComp
            className="home__content-wrap-tabs"
            activeTab={activeTab}
            onTabClick={({ key }) => {
              setActiveTab(key);
            }}
            data={data}
            page={4}
          />
          <div className="card-item__html-content">
            {activeTab === 0 ? (
              <div
                dangerouslySetInnerHTML={{
                  __html:
                    _.find(list, (item) => item.code === goodsSelect)
                      ?.purchaseNotes ||
                    "<p style='text-align: center'>暂无数据</p>",
                }}
              />
            ) : (
              <div
                dangerouslySetInnerHTML={{
                  __html:
                    _.find(list, (item) => item.code === goodsSelect)
                      ?.usageIllustration ||
                    "<p style='text-align: center'>暂无数据</p>",
                }}
              />
            )}
          </div>
        </div>
      </div>
      <Footer
        btnText="立即购买"
        shop={shop}
        redirectOrder={() => (window.location.href = '/order.html')}
        showKFModal={_.debounce(() => {
          Modal.alert(
            <div className="modalTop">
              咨询商品问题,请添加客服QQ(2045879978)
            </div>,
            '',
            [
              {
                text: '我知道了',
                onPress: () => {},
              },
            ]
          );
        }, 100)}
      >
        {_.find(list, (item) => item.code === goodsSelect)?.facePrice -
          _.find(list, (item) => item.code === goodsSelect)?.price >
          0 && (
          <div className="item-footer__btn-tags">
            立省
            {getFloat(
              ((_.find(list, (item) => item.code === goodsSelect)?.facePrice -
                _.find(list, (item) => item.code === goodsSelect)?.price) *
                amount) /
                10000,
              PRECISION
            )}
            元
          </div>
        )}
      </Footer>

      <form id="pay_form" action={payUrl} method="post" ref={formRef}>
        <input
          id="order_info"
          type="text"
          name="orderInfo"
          value={orderInfo}
          style={{ display: 'none' }}
        />
      </form>
    </>
  );
};
